apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hashimoto-pcos-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: hashimoto.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hashimoto-pcos-service
                port:
                  number: 80
