import { normalizeIngredientName } from "./ingredient-normalization";

export type CanonicalIngredientKey = typeof INGREDIENT_ALIASES[keyof typeof INGREDIENT_ALIASES];

export interface IngredientAliasMatch {
  input: string;
  normalizedInput: string;
  canonicalKey: CanonicalIngredientKey;
}

export const INGREDIENT_ALIASES = {
  zucker: "sugar",
  sugar: "sugar",
  sucre: "sugar",
  saccharose: "sugar",
  sucrose: "sugar",
  dextrose: "dextrose",
  traubenzucker: "dextrose",
  "sucre de raisin": "dextrose",
  glukosesirup: "glucose-syrup",
  "glucose syrup": "glucose-syrup",
  "sirop de glucose": "glucose-syrup",
  fruktosesirup: "fructose-syrup",
  "fructose syrup": "fructose-syrup",
  "sirop de fructose": "fructose-syrup",
  invertzucker: "invert-sugar",
  "invert sugar": "invert-sugar",
  "sucre inverti": "invert-sugar",
  milch: "milk",
  milk: "milk",
  lait: "milk",
  joghurt: "yogurt",
  yogurt: "yogurt",
  yaourt: "yogurt",
  kasein: "casein",
  casein: "casein",
  caseine: "casein",
  molke: "whey",
  whey: "whey",
  lactoserum: "whey",
  kase: "cheese",
  cheese: "cheese",
  fromage: "cheese",
  weizenmehl: "wheat-flour",
  "weizen mehl": "wheat-flour",
  "wheat flour": "wheat-flour",
  "farine de ble": "wheat-flour",
  weizenvollkornmehl: "whole-wheat-flour",
  "whole wheat flour": "whole-wheat-flour",
  "farine complete de ble": "whole-wheat-flour",
  roggen: "rye",
  rye: "rye",
  seigle: "rye",
  gerste: "barley",
  barley: "barley",
  orge: "barley",
  soja: "soy",
  soy: "soy",
  sojaeiweiss: "soy-protein",
  "soy protein": "soy-protein",
  "proteine de soja": "soy-protein",
  tofu: "tofu",
  tempeh: "tempeh",
  miso: "miso",
  lachs: "salmon",
  salmon: "salmon",
  saumon: "salmon",
  makrele: "mackerel",
  mackerel: "mackerel",
  maquereau: "mackerel",
  fischol: "fish-oil",
  "fish oil": "fish-oil",
  "huile de poisson": "fish-oil",
  leinsamen: "flaxseed",
  flaxseed: "flaxseed",
  linseed: "flaxseed",
  "graine de lin": "flaxseed",
  chiasamen: "chia-seed",
  "chia seed": "chia-seed",
  "graine de chia": "chia-seed",
  mandel: "almond",
  almond: "almond",
  amande: "almond",
  walnuss: "walnut",
  walnut: "walnut",
  noix: "walnut",
  haselnuss: "hazelnut",
  hazelnut: "hazelnut",
  noisette: "hazelnut",
  erdnuss: "peanut",
  peanut: "peanut",
  cacahuete: "peanut",
  sesam: "sesame",
  sesame: "sesame",
  lentille: "lentil",
  linse: "lentil",
  lentil: "lentil",
  kichererbse: "chickpea",
  chickpea: "chickpea",
  "pois chiche": "chickpea",
  bohne: "bean",
  bean: "bean",
  haricot: "bean",
  alge: "seaweed",
  seaweed: "seaweed",
  algue: "seaweed",
  nori: "nori",
  kelp: "kelp",
  jodsalz: "iodized-salt",
  "iodized salt": "iodized-salt",
  "sel iode": "iodized-salt",
  aspartam: "aspartame",
  aspartame: "aspartame",
  sucralose: "sucralose",
  stevia: "stevia",
  erythrit: "erythritol",
  erythritol: "erythritol",
  xylit: "xylitol",
  xylitol: "xylitol",
  lecithin: "lecithin",
  lecithine: "lecithin",
  e322: "lecithin",
  "soy lecithin": "soy-lecithin",
  "soja lecithin": "soy-lecithin",
  "soy-lecithin": "soy-lecithin",
  carrageen: "carrageenan",
  carrageenan: "carrageenan",
  carraghenane: "carrageenan",
  e407: "carrageenan",
} as const satisfies Readonly<Record<string, string>>;

export function resolveIngredientAlias(input: string): IngredientAliasMatch | null {
  const normalizedInput = normalizeIngredientName(input);
  const rawKey = (INGREDIENT_ALIASES as Readonly<Record<string, string>>)[normalizedInput];
  if (!rawKey) return null;
  const canonicalKey = rawKey as CanonicalIngredientKey;
  return { input, normalizedInput, canonicalKey };
}
