// scripts/ingredient-data.js
// Comprehensive known ingredient names for German/European food products.
// Used by build-db.mjs to filter garbage from normalized ingredient segments.

// ── German ingredient names ────────────────────────────────────────────────────
const GERMAN = new Set([
  // Zucker & Süßungsmittel
  'zucker','saccharose','glucose','dextrose','fruktose','fruktose','lactose','maltose',
  'raffinierter zucker','rohrzucker','vollrohrzucker','rohrzuckersirup','zuckersirup','invertzuckersirup',
  'glukosesirup','glukose-fruktose-sirup','fruktosesirup','maisstärkesirup','reissirup',
  'agavendicksaft','agavensirup','honig','bienenhonig','birnenmost','birnendicksaft',
  'apfeldicksaft','apfelsaftkonzentrat','malzextrakt','malzodextrin','malz',
  'stevia','steviolglycoside','erythrit','xylit','birkenzucker','sorbit','mannit',
  'isomalt','maltit','tagatose','süßungsmittel','süßstoff',

  // Mehle & Stärken
  'weizenmehl','weizenvollkornmehl','weizenstärke','weizeneiweiß','weizengluten',
  'roggenmehl','roggenvollkornmehl','roggenstärke','gerstenmehl','gerstenmalz',
  'hafermehl','haferflocken','haferkleie','dinkelmehl','dinkelvollkornmehl','dinkelstärke',
  'buchweizenmehl','buchweizen','hirsemehl','hirse','quinoa','quinoamehl','amaranth',
  'maismehl','maisstärke','maisgrieß','polenta','kartoffelstärke','kartoffelmehl',
  'reismehl','reisstärke','reisgrieß','klebreis','reis','reis gepufft','puffreis','gepuffter mais',
  'tapiokastärke','tapiokamehl',
  'kokosmehl','mandelmehl','haselnussmehl','paranussmehl','sojamehl','sojabohnenmehl',
  'lupinenmehl','lupinenprotein','mehl','stärke','modifizierte stärke','veränderte stärke',

  // Öle & Fette
  'palmöl','palmin','palmfett','palmenfett','kokosöl','kokosfett','kokosnussöl',
  'sonnenblumenöl','sonnenblumenfett','rapsöl','rapsfett','rebornöl',
  'olivenöl','natives olivenöl extra','olivenöl extra vergine','olivenfruchtöl',
  'maiskeimöl','maisöl','weizenkeimöl','weizenkeimöl','sojaöl','sojabohnenöl',
  'erdnussöl','arachisöl','walnussöl','haselnussöl','mandelöl','sesamöl','sesamfett',
  'mohnöl','leinsamenöl','hanföl','distelöl','safloröl','traubenkernöl',
  'avocadoöl','brasilianussöl','macadamiaöl','pistazienöl','pecanöl',
  'tierisches fett','schweinefett','schmalz','gänsefett','entenfett','butterreinfett',
  'ghee','butter','butterfett','milchfett','rahm','sahne','schlagsahne','sauerrahm',
  'creme','crème fraîche','margarine','pflanzenmargarine','streichfett',
  'fett','öl','öle','fette',

  // Milch & Milchprodukte
  'milch','vollmilch','teilentrahmte milch','entrahmte milch','milchpulver',
  'magermilchpulver','vollmilchpulver','sahne','schlagsahne','kondensmilch',
  'milchkonzentrat','molkepulver','molke','molkenprotein','molkenproteinpulver',
  'casein','natriumcaseinat','calciumcaseinat','caseinat','micellar casein',
  'käse','hartkäse','weichkäse','schnittkäse','schmelzkäse','käsepulver',
  'parmesan','pecorino','grana padano','gouda','emmentaler','bergkäse',
  'brie','camembert','mozzarella','ricotta','quark','körnig','hüttenkäse',
  'schichtkäse','smetana','crème fraîche','saure sahne','sauerrahm',
  'joghurt','naturjoghurt','griechischer joghurt','joghurtpulver','joghurtkultur',
  'kefir','kefirpilz','buttermilch','buttermilchpulver','ayran',
  'milchprotein','milcheiweiß','milchzucker','laktose','laktoseintoleranz',
  'laktalbumin','laktoglobulin','calciumlactat','calciumlaktat','milchsäure','milchsäurebakterien',

  // Eier
  'ei','eier','eiklar','eiweiß','eidotter','eigelb','vollei','volleier',
  'eiweißpulver','eiweißkonzentrat','trockenei','eiextrakt','eipulver',
  'hühnerei','hühnereier','wachtelei','wachteleier',

  // Fleisch
  'rindfleisch','rind','rindhack','rinderhackfleisch','rindfleischextrakt',
  'schweinefleisch','schwein','schweinehack','schweinehackfleisch','schweinebauch',
  'hähnchen','hähnchenfleisch','huhn','hühnerfleisch','hühnerbrust','hühnerschenkel',
  'pute','putenfleisch','putenbrust','putenschenkel','truthahn',
  'lamm','lammfleisch','lammhack','lammkeule','lammrücken',
  'ziege','ziegenfleisch','ziegenkäse','ziegenmilch',
  'wild','wildbret','hirsch','reh','wildschwein','kaninchen','hasen',
  'fisch','fischfleisch','fish','fleisch','fleischextrakt','fleischbrühe',
  'gelatine','rindergelatine','schweinegelatine','gelatinepulver',

  // Fisch & Meeresfrüchte
  'lachs','lachsfilet','wildlachs','lachskaviar','rogen','kaviar',
  'forelle','regenbogenforelle','saibling','renke','renken',
  'makrele','hering','hering','sardine','sardellen','anchovis','ansjovis',
  'thunfisch','tunfisch','bonito','schwertfisch','seelachs','kabeljau','dorsch',
  'seehecht','hechtdorsch','wolfsbarsch','barsch','zander','hecht',
  'seelebewesen','garnele','garnelen','shrimp','shrimps','krabbe','krabben',
  'hummer','lobster','miesmuschel','miesmuscheln','austern','schnecken',
  'calamari','tintenfisch','sepie','octopus','pulpo',
  'fischöl','fischleberöl','cod liver oil','dorschlebertran',
  'algen','algenöl','algenpulver','spirulina','chlorella','wakame','nori',
  'pektin',

  // Gemüse (roh & verarbeitet)
  'tomate','tomaten','tomatenmark','tomatenkonzentrat','tomatenpulver',
  'trockentomaten','getrocknete tomaten','tomatenextrakt',
  'paprika','paprikapulver','paprikaflocken','chili','chilipulver','chiliflocken',
  'cayenne','peperoni','peperoncini','pimiento',
  'karotte','karotten','möhre','möhren','möhrensaft','karottensaft',
  'zwiebel','zwiebeln','schalotte','schalotten','lauch','porree','lauchzwiebel',
  'knoblauch','knoblauchpulver','knoblauchgranulat',
  'kohl','weißkohl','rotkohl','sauerkraut','krauts','blumenkohl','brokkoli',
  'rosenkohl','wirsing','kopfkohl','rotkohl','staudensellerie','sellerie',
  'sellerie','sellerieblätter','selleria','staudenselleriesaft',
  'spargel','chicoree','endivie','radieschen','rettich','meldung','mangold',
  'spinat','tiefkühlspinat','spinatpulver',
  'gurke','gurken','cornichons','einlegegurke',
  'avocado','avocadoöl',
  'artischocke','aubergine','auberginen','fenchel','fenchelsamen',
  'kürbis','kürbiskernöl','kürbiskerne','kürbiskernmehl',
  'zucchini','courgette','courgetti',
  'erbsen','erbsenprotein','erbsenisolat','erbsenmehl','markerbsen',
  'bohnen','bohnenmehl','gartenbohne','prinzessbohne','fisolen','grüne bohnen',
  'linsen','linsenmehl','rote linsen','grüne linsen','bergbohnen',
  'kichererbsen','kichererbsenmehl','humus','humus','tahini','sesampaste',
  'sojabohnen','sojabohnenmehl','edamame','sojakeime','sojasprossen',
  'mungobohnen','adzukibohnen','limabohnen','kidneybohnen',
  'pilze','champignons','pfifferlinge','steinpilze','maronen','trüffel',
  'sprossen','keimlinge','samen','sprossenmix',

  // Obst (roh & verarbeitet)
  'apfel','äpfel','apfelsaft','apfelmark','apfeldicksaft','apfelkonzentrat',
  'birne','birnen','birnensaft','birnenmark',
  'banane','bananen','bananenpulver','getrocknete bananen',
  'orange','apfelsine','orangensaft','orangensaftkonzentrat',
  'zitrone','zitronensaft','zitronensaftkonzentrat','zitronenabrieb','zitronenöl',
  'limette','limettensaft',
  'traube','trauben','traubensaft','weintrauben','rosinen','korinthen',
  'kernen','cranberry','cranberrysaft','preiselbeeren','preiselbeermarmelade',
  'heidelbeere','heidelbeeren','blauberry','brombeere','brombeeren',
  'himbeere','himbeeren','erdbeere','erdbeeren','erdbeermark',
  'kirschbaum','kirschen','sauerkirschen','morellen',
  'pfirsich','pfirsiche','nektarine','nectarines','aprikose','aprikosen',
  'pflaume','pflaumen','zwetschge','zwetschgen','mirabelle','mirabellen',
  'mango','mangos','mangopüree','mangokonzentrat',
  'ananas','ananassaft','ananasstücke','ananasmark',
  'papaya','papayapulver','passionsfrucht','maracuja','granatapfel','granatapfelsaft',
  'kokosnuss','kokosraspel','kokosfruchtfleisch','kokosmilch','kokoswasser','kokosmus','kokosflocken','wasser',
  'feige','feigen','dattel','datteln','dattelpaste',
  'frucht','früchte','fruchtmark','fruchtextrakt','fruchtpulver',
  'fruchtkonzentrat','fruchtsaft','fruchtzubereitung','fruchtpaste',

  // Nüsse & Samen
  'mandel','mandeln','mandelmus','mandelöl','mandelmehl','blanchierte mandeln',
  'haselnuss','haselnüsse','haselnussmus','haselnussöl','haselnussmehl',
  'walnuss','walnüsse','walnussöl',
  'paranuss','paranüsse','brasilianernuss',
  'cashew','cashewkerne','cashewmus','cashewöl',
  'pistazie','pistazien','pistazienmus','pistazienöl',
  'pecan','pecannüsse','macadamia','macadamianüsse','macadamiaöl',
  'erdnuss','erdnüsse','erdnussöl','erdnussmus','erdnussmehl','entölte erdnüsse',
  'sonnenblumenkerne','sonnenblumenkernmehl','sonnenblumenöl',
  'kürbiskerne','kürbiskernöl','kürbiskernmehl',
  'leinsamen','leinsamenmehl','leinsamenöl','hanfsamen','hanföl','hanfmehl',
  'chia','chia samen','chiaöl','chiasamen',
  'sesam','sesamsamen','sesamöl','tahini','sesampaste',
  'mohn','mohnsamen','mohnöl','sultaninen','johannisbrot','johannisbrotkernmehl',
  'Flohsamen','flohsamenschalen','psyllium','psyllium husk',

  // Kräuter & Gewürze
  'pfeffer','pfefferkorn','schwarzer pfeffer','weißer pfeffer','grüner pfeffer',
  'chili','chiliflocken','chilipulver','cayennepfeffer','chilischote',
  'paprika','edelsüßpaprika','rosenscharfem paprika','paprikapulver',
  'kurkuma','kurkumaextrakt','curcuma','curcumin',
  'ingwer','ingwerwurzel','ingwerpulver','ingwerextrakt','candied ginger',
  'knoblauch','knoblauchpulver','knoblauchgranulat',
  'zwiebel','zwiebelpulver','onion powder',
  'muskat','muskatnuss','macis','mace',
  'kardamom','kardamomkapseln','elettaria',
  'nelke','nelken','gewürznelken','stem und',
  'zimt','zimtrinde','ceylon zimt','cassia zimt','cinnamon',
  'anisbio','anis','sternanis','fenchelsamen','fenchel',
  'koriander','koriandersamen','korianderpulver','coriander',
  'kümmel','kümmelsamen','caraway','kmín',
  'thyme','thymian','rosemary','rosmarin','oregano','basilikum','basil',
  'petersilie','petersil','dill','schnittlauch','baguette','lovage','liebstöckel',
  'majoran','salbei','minze','pfefferminze','menthe','peppermint',
  'bergkümmel','schwarzkümmel','cumé','cumino',
  'safran','saffron','vanille','vanilleschote','vanilleextrakt','vanillin',
  'sumach','sumak','agretti',

  // Gewürzmischungen
  'gewürze','gewürzextrakte','gewürzmischung','curry','masala','garam masala',
  'tandoori','ras el hanout','zahtar','herbes de provence',

  // Getränke & Extrakte
  'kaffee','kaffeepulver','kaffeextrakt','kaffeebohnen','kaffeemehl',
  'löslicher kaffee','instantkaffee','espresso','espressopulver',
  'tees','tee','teeblätter','teepulver','grüner tee','schwarzer tee',
  'früchtetee','kräutertee','rooibos','honeybush',
  'kakaopulver','kakao','kakaomasse','kakaobutter','kakaogranulat','cacao',
  'cacaopulver','cacaomasse','rohkakao','kakaoextrakt',
  'schokolade','zartbitterschokolade','vollmilchschokolade','blockschokolade','schokoladenflocken','kuvertüre',
  'schokoladenkuvertüre','schokoladenmasse',
  'malzkaffee','malzextrakt','malzkaffee','cerealienkaffee',
  'gerstenmalz','gerstenextrakt','hopfen','hopfenextrakt',
  'rosmarinnextrakt','rosmarin','rosmarin-extrakt',
  'grapefruitextrakt','rosinenextrakt','weintraubenextrakt',

  // Fermentierte Produkte
  'tempeh','tempeh','miso','misopaste','misoextrakt',
  'sojasauce','sojasoße','shoyu','tamari',
  'fermentierte sojabohnen','fermentierte schwarze bohnen','douchi',
  'kefir','kimchi','sauerkraut','tempeh','fermentiertes',
  'essig','weinessig','apfelessig','balsamessig','balsamico',
  'branntweinessig','reissessig','weinessig','rotweinessig',
  'reifegas',

  // Hülsenfrüchte
  'sojaprodukt','sojadrink','sojamehl','sojabohnen','sojaprotein',
  'sojaproteinisolat','sojaproteinkonzentrat','sojaeiweiß','sojagranulat',
  'sojalezithin','sojalecithin','sojabohnenlecithin',
  'tofu','tofuprodukt','seidentofu','fest tofu','tauhu',
  'edamame','bean sprouts','sprossen','sojasprossen',

  // Nahrungsergänzung
  'protein','proteinpulver','proteinisolat','proteinkonzentrat',
  'molkenprotein','molkenproteinisolat','whey protein','whey protein isolate',
  'kollagen','kollagenpeptide','kollagenhydrolysat',
  'kreatin','kreatinmonohydrat','beta-alanin','bcaa','aminosäuren',
  'vitamin','vitamine','vitaminkonzentrat','vitaminpulver',
  'vitamin c','ascorbinsäure','vitamin d','cholecalciferol','vitamin d3',
  'vitamin e','tocopherol','tocopherolkonzentrat','vitamin k','phylloquinon',
  'vitamin b1','thiamin','thiaminhydrochlorid','vitamin b2','riboflavin',
  'vitamin b3','niacin','niacinamid','vitamin b5','pantothensäure',
  'vitamin b6','pyridoxin','pyridoxinhydrochlorid','vitamin b7','biotin',
  'vitamin b9','folsäure','folat','vitamin b12','cobalamin','cyanocobalamin',
  'vitamin b12','cobalamin','methylcobalamin','inosit','inositol',
  'mineralien','mineralstoffe','spurenelemente',
  'calcium','calciumcarbonat','calciumcitrat','calciumphosphat',
  'magnesium','magnesiumcitrat','magnesiumcarbonat','magnesiumsulfat',
  'zink','zinkcitrat','zinkglukonat','zinksulfat','zinkmethionin',
  'eisen','eisengluconat','eisenfumarat','eisensulfat','bisglycinat',
  'selen','selenomethionin','natriumselenat','selenium','selenhefe',
  'chrom','chrompicolinat','chromchlorid','chromium','chrom III',
  'jod','jodid','kaliumjodat','jodiertes speisesalz','kaliumjodid',
  'kupfer','kupfergluconat','kupfersulfat',
  'mangan','mangangluconat','mangansulfat',
  'molybdän','natriummolybdat',
  'omega-3','omega-3-fettsäuren','omega-3-fettsäurekonzentrat',
  'epa','dhea','dha','algenöl','fish oil','fish oil concentrate',
  'carnitin','l-carnitin','acetyl-l-carnitin',
  'coenzym','coenzym q10','ubichinon','ubidecarenon',
  'melatonin','tryptophan','5-htp','gaba','gaba',
  'probiotika','probiotische kulturen','milchsäurebakterien',
  'ballaststoffe','ballaststoff','darmflora','präbiotika','inulin',
  'pektin','resistant starch','psyllium','flohsamen','psylliumsamen',
  'koffein','coffein','koffeinpulver',

  // Enzyme
  'enzyme','enzym','pektinase','lactase','laktase','amylase','protease',
  'lipase','glucoamylase','transglutaminase','papain','bromelain',

  // Lebensmittelzusatzstoffe (legitim)
  'lecithin','sojalecithin','sonnenblumenlecithin','rapslecithin','raps-lecithin',
  'emulgator','emulgatoren',
  'säuerungsmittel','citronensäure','zitronensäure',
  'äpfelsäure','weinsäure','milchsäure','fumarsäure','phosphorsäure',
  'natriumcitrat','kaliumcitrat','calciumcitrat',
  'natriumcarbonat','natriumhydrogencarbonat','soda','natron',
  'kaliumcarbonat','kaliumhydrogencarbonat',
  'calciumcarbonat','kalk','kreide',
  'magnesiumcarbonat','magneisa','magnesiumoxid',
  'natriumsulfat','calciumsulfat','gips',
  'carbamide','harnstoff',
  'salz','speisesalz','meersalz','jodsalz','jodiertes speisesalz',
  'natriumchlorid','calciumchlorid','magnesiumchlorid','kaliumchlorid',
  'phosphat','natriumphosphat','calciumphosphat','dicalciumphosphat',
  'polyphosphat','natriumpolyphosphat','tripolyphosphat',
  'diphosphat','natriumdiphosphat','dinatriumdiphosphat',
  'natriumnitrit','natriumnitrat','kaliumnitrat',
  'sulfit','natriumsulfit','natriummetabisulfit','schwefeldioxid',
  'konservierungsstoff','konservierungsmittel','säureregulator',
  'feuchthaltemittel','festigungsmittel',
  'sorbat','kaliumsorbat','natriumsorbat','sorbinsäure',
  'benzoat','natriumbenzoat','kaliumbenzoat','benzoesäure',
  'natamycin','nisin',
  'antioxidant','ascorbinsäure','vitamin c',
  'natriumascorbat','calciumascorbat',
  'tocopherol','tocopherolkonzentrat','vitamin e',
  'rosmarinnextrakt','rosmarin','rosmarin-extrakt','rosmarinextrakt',
  'citrat','acetat','tartrat','laktat','malat','fumarat',
  'natriumacetat','calciumacetat','kaliumacetat',
  'natriumtartrat','kaliumtartrat','cream of tartar',
  'guarkernmehl','guar','guarmehl','tara','taramind','tamarindenextrakt',
  'xanthan','xanthan gum','xanthanpulver',
  'carrageen','carrageenan','iota-carrageen','kappa-carrageen',
  'agar','agar-agar','pektin','amid','c methylcellulose','mc',
  'hydroxypropylcellulose','hyprolose','hypromellose','hmc',
  'carboxymethylcellulose','cellulose','cellulosegummi',
  'natriumcarboxymethylcellulose','acetyliert','stärke',
  'acetyliertes distärke','phosphatierte distärke','hydroxypropylstärke',
  'modifizierte stärke','getaktete stärke','vliestärke',
  'sonnenblumenwachs','candelillawachs','carnaubawachs','bienenwachs',
  'füllstoff','trägerstoff','träger','füllstoffe',
  'trennmittel','trennmittel','siliciumdioxid','silica','silicagel',
  'calciumsilicat','magnesiumsilicat','talk','talkum',
  'süßungsmittel','süßstoff','zuckeraustauschstoff','zuckeraustauschstoffe',
  'neohesperidin','steviolglycoside','steviaextrakt','stevia',
  'saccharin','saccharinnatrium','cyclamat','cyclamatnatrium',
  'aspartam','aspartamacesulfam','salz','acesulfam','acesulfam k','ack',
  'sucralose','trichlorogalactosucrose','thumarin','taumatine',
  'panmol','braunalgenextrakt','litesse','polydextrose',
  'fruchtzubereitung','fruchtgrundstoff','fruchtkonzentrat','fruchtmark',

  // Aromen
  'aroma','aromen','natürliches aroma','natürliche aromen','natürliche aroma',
  'naturidentisches aroma','künstliches aroma','aromaextrakt',
  'vanille','vanilleextrakt','vanillin','ethylvanillin',
  'lecitin','lecitinhaltig','sojalecithin','rapslecitin','sonnenblumenlecitin',
  'säuerungsmittel','antioxidationsmittel','farbstoff','farbstoffe',
  'emulgator','emulgatoren','stabilisator','stabilisatoren',
  'verdickungsmittel','konservierungsstoff','konservierungsmittel',
  'süßungsmittel','süßstoff','rauch','rauch-aroma','rauchflüssigkeit',
  'trägerstoff','füllstoff','füllmittel','trennmittel',
  'zimt','cinnamon','cumarin','kumarin',
  'kakaoaroma','schokoladenaroma','kaffeearoma','malzaroma',
  'fruchtaroma','beerenaroma','zitrusaroma','orangen aroma',
  'rauch','rauch aroma','smoke','wood smoke','rauchflüssigkeit','rauchkondensat',

  // Farbstoffe
  'farbstoff','farbstoffe','lebensmittelfarbe','lebensmittelfarbstoff',
  'annatto','annattoextrakt','bixin','norbixin','e160b',
  'karmin','cochineal','cochinealextrakt','e120','czerw',
  'paprikaextrakt','paprikafarbstoff','capsanthin','e160c',
  'curcumin','turmereic','e100','curcumin','kurkuma',
  'beta-carotin','betacarotin','e160a','carotin','carotene',
  'lycopin','lycopen','e160d','tomatenfarbstoff',
  'chlorophyll','chlorophyllin','e140','spirulina','e140',
  'zuckerkulör','caramel','e150a','e150b','e150c','e150d','ammoniak',
  'titandioxid','titanium dioxide','e171','tio2',
  'eisenoxid','eisenoxide','e172','rouge','rot','gelb',
  'riboflavin','vitamin b2','e101','lactoflavin',
  'tartrazin','e102','chinolin','e104','schoenfei','e110',
  'azur','e131','indigo','e132','indigotin','e133','brilliant blue',
  'e150','e151','e154','e155','e160','e161','e162','e163',
  'titan','e171','aluminium','e173','silber','e174','gold','e175',
  'lutein','zeaxanthin','e161b','e161h',

  // Futtermittel / Diverse
  'hefe','hefeprodukt','hefeextrakt','hefepulver','hefekonzentrat',
  'hefeautolysat','yeast','bakery yeast','bäckerhefe','hefeflocken',
  'malz','malzextrakt','malzmehl','malzsyrup','malt','malt extract',
  'malzkeime','malt germs','malzfuß','mouture',
  'zuckerrüben','zuckerrübenschnitzel','rübenschnitzel',
  'fruchtkerne','fruchtstein','aprikosenkerne','pfirsichkerne',
  'weizenkleie','reiskleie','haferkleie','kleie','bran',
  'keime','keimlinge','keimöle','germ oil','keimling','sprossen',
  'cerealien','getreide','getreidemehl','getreideprodukt',
  'getreidefasern','ballaststoffmischung','faserstoffe',

  // Sonstige Lebensmittelzutaten
  'backpulver','hefebackpulver','natron','natriumbicarbonat',
  'ammoniumcarbonat','hirse','ammoniumbicarbonat','hirschhornsalz',
  'stärke','maisstärke','kartoffelstärke','tapiokastärke',
  'tinte','sepia','calamari','calamaritinte',
  'essig','weinessig','apfelessig','balsamico','reissessig',
  'gelatine','rindergelatine','schweinegelatine','fischgelatine',
  'speck','bacon','schinken','rohschinken','kochschinken','pastete',
  'fleisch','rindfleisch','schweinefleisch','hackfleisch','faschiertes',
  'agar','agar-agar','pektin','carrageen','xanthan','gummi arabicum',
  'gummi','gummi arabicum','akaziengummi','tragant','taragummi',
  'cystein','l-cystein','cysteinhydrochlorid','luminescent',
  'gluten','weizengluten','roggengluten','gerstengluten','maisgluten',
  'weizenprotein','maisprotein','reisprotein','erbsenprotein','sojaprotein',
  'protein','eiweiß','albumin','eialbumin','blutalbumin',
  'kollagen','gelatine','gelatinehydrolysat','kollagenpeptide',
  'milchprotein','molkenprotein','casein','kasein','kaseinat',
  'sojaeiweiß','toful','textured vegetable protein','tvp',
  'seitan','weizeneiweiß','weizenfleisch','wheat meat',
  'invertase','glucose-oxidase','glucose isomerase','xylose isomerase',
  'papain','bromelain','ficin','actinidin','protease',
  'pektinesterase','cellulase','hemicellulase','mannase',
  'beta-glucan','glucan','beta-glucane','beta glucan',
  'saponine','saponin','quillaja','quillajaextrakt',
  'tannine','tannin','gallussäure','gerbsäure','pyrogallol',

  // Alkohol & Destillate
  'ethanol','alkohol','weingeist','spiritus',
  'weindestillat','obstbrand','branntwein','corn distillers',
  'aroma','rum','vanilleextrakt in alkohol',

  // Meeresalgen (significant for this project)
  'algen','algenmehl','algenextrakt','algenpulver','spirulina','spirulinapulver',
  'chlorella','chlorellapulver','wakame','wakamemehl','nori','norialgen',
  'dulse','irish moss','kelp','kombu','seagrass','seegras',
  'Agar','agar agar','agarine','ascophyllum','ascophyllumm',

  // Begleitstoffe / Träger
  'trägerstoff','träger','füllstoff','füllmittel',
  'siliciumdioxid','silikagele','silica','kieselsäure','silicagel',
  'calciumsilicat','magnesiumsilicat','talk','talkum','gips',
  'cellulose','mikrokristalline cellulose','mcc','cellulosepulver',
  'stärke','maisstärke','modifizierte stärke','trockene glukosesirup',
  'maltodextrin','glukosemaltodextrin','syrup solids',
  'mannitol','sorbitol','xylit','erythrit','isomalt','maltit',
  'gummi arabicum','akaziengummi','arabisches gummi','senegal gummi',
]);

// ── English ingredient names (also common in DACH products) ─────────────────
const ENGLISH = new Set([
  'water','salt','sugar','dextrose','glucose','fructose','lactose','maltose',
  'sucrose','milk','cream','butter','cheese','yogurt','egg','eggs',
  'egg white','egg yolk','whey','whey protein','casein','sodium caseinate',
  'flour','wheat flour','rye flour','barley','oat','oats','spelt','buckwheat',
  'quinoa','amaranth','millet','rice','corn','maize','potato','tapioca',
  'soy','soybean','soy protein','soy lecithin','soybean oil','soy flour',
  'tofu','tempeh','miso','soy sauce','shoyu','tamari','edamame',
  'sunflower oil','sunflower seed','sunflower lecithin',
  'palm oil','palm fat','coconut oil','coconut milk','coconut cream',
  'olive oil','rapeseed oil','canola','corn oil','maize oil',
  'sesame','sesame oil','sesame seeds','tahini',
  'flax','flaxseed','linseed','flax oil','flaxseed oil',
  'hemp','hemp oil','hemp seed','hemp protein',
  'walnut','walnut oil','hazelnut','hazelnut oil','almond','almond oil',
  'cashew','pecan','macadamia','pistachio','pine nut',
  'peanut','peanut oil','peanut butter','groundnut',
  'apple','orange','lemon','lime','grape','cherry','strawberry',
  'blueberry','raspberry','blackberry','cranberry','currant',
  'banana','mango','papaya','pineapple','peach','apricot','plum',
  'date','fig','raisin','coconut','coconut water','coconut flesh',
  'carrot','onion','garlic','leek','shallot','pepper','chili',
  'cabbage','broccoli','cauliflower','kale','spinach','celery',
  'tomato','cucumber','lettuce','artichoke','asparagus','eggplant',
  'zucchini','pumpkin','squash','mushroom','mushrooms','champignon',
  'beetroot','beet','radish','turnip','fennel','parsley','coriander',
  'basil','oregano','thyme','rosemary','sage','mint','dill','chive',
  'cumin','coriander seed','coriander powder','turmeric','curcuma',
  'ginger','nutmeg','mace','cardamom','clove','cinnamon','vanilla',
  'cocoa','cacao','chocolate','cocoa butter','cocoa mass','cocoa powder',
  'coffee','espresso','tea','green tea','black tea',
  'honey','maple syrup','agave','molasses','malt','malt extract',
  'yeast','yeast extract','baking powder','bicarbonate','sodium bicarbonate',
  'gelatin','gelatine','collagen','collagen peptides',
  'fish','salmon','tuna','cod','sardine','anchovy','herring','mackerel',
  'shrimp','prawn','crab','lobster','scallop','mussel','clam','oyster',
  'algae','spirulina','chlorella','wakame','nori','kelp','dulse',
  'meat','beef','pork','lamb','mutton','chicken','turkey','duck','goose',
  'bacon','ham','sausage','minced meat','ground meat',
  'liver','kidney','heart','tongue','tripe',
  'vinegar','wine vinegar','apple cider vinegar','balsamic',
  'soybean','soy protein isolate','soy protein concentrate',
  'whey protein isolate','whey protein concentrate',
  'milk protein','milk protein concentrate','milk powder',
  'skimmed milk powder','skim milk powder','whole milk powder',
  'cream powder','buttermilk powder','caseinate',
  'pectin','carrageenan','agar','xanthan gum','guar gum','locust bean gum',
  'gum arabic','acacia gum','tara gum','tamarind','tamarind seed gum',
  'cellulose','microcrystalline cellulose','mcc','carboxymethyl cellulose','cmc',
  'modified starch','acetylated starch','phosphated starch','hydroxypropyl starch',
  'tapioca starch','potato starch','corn starch','maize starch','wheat starch',
  'lecithin','sunflower lecithin','rapeseed lecithin','soy lecithin',
  'emulsifier','emulsifiers','stabilizer','stabilizers',
  'thickener','thickening agent','gelling agent',
  'citric acid','sodium citrate','potassium citrate','calcium citrate',
  'ascorbic acid','sodium ascorbate','calcium ascorbate','vitamin c',
  'tocopherol','tocopherols','vitamin e','mixed tocopherols',
  'beta-carotene','carotene','carotenoid','lutein','zeaxanthin',
  'sorbic acid','potassium sorbate','sodium sorbate','benzoate','sodium benzoate',
  'sulfur dioxide','sulphite','sodium sulphite','sodium metabisulphite',
  'nitrite','sodium nitrite','nitrate','sodium nitrate','potassium nitrate',
  'edta','calcium edta','disodium edta',
  'phosphate','sodium phosphate','calcium phosphate','diphosphate',
  'polyphosphate','sodium polyphosphate','tripolyphosphate',
  'salt','sea salt','rock salt','iodized salt','sodium chloride',
  'monosodium glutamate','msg','glutamate','yeast extract','autolyzed yeast',
  'protein','protein powder','protein isolate','protein concentrate',
  'food coloring','color','colour','annatto','bixin','norbixin',
  'carminic acid','cochineal','carmine','e120',
  'paprika extract','capsanthin','turmeric','curcumin','curcuma',
  'sugar','syrup','glucose syrup','high fructose corn syrup','hfcs',
  'invert sugar','inverted sugar syrup','molasses','treacle',
  'polydextrose','inulin','fructo-oligosaccharide','fructan','oligofructose',
  'resistant starch','rs2','rs3','type resistant starch',
  'alpha-galactosidase','beta-galactosidase','lactase',
  'amylase','protease','lipase','cellulase','glucoamylase',
  'papain','bromelain','ficin','actinidin','microbial rennet',
  'biotin','folic acid','folate','niacin','niacinamide',
  'pantothenic acid','pyridoxine','riboflavin','thiamine','thiamin',
  'cobalamin','cyanocobalamin','methylcobalamin',
  'cholecalciferol','ergocalciferol','vitamin d','vitamin d3',
  'phylloquinone','menaquinone','menaquinone-7','vitamin k','vitamin k2',
  'alpha-tocopherol','mixed tocopherols','tocopherol','tocopheryl acetate',
  'retinol','retinyl acetate','retinyl palmitate','vitamin a',
  'ascorbyl palmitate','vitamin c ester',
  'omega-3','omega-6','omega-9','dha','epa','ala','linoleic acid','cla',
  'fish oil','fish oil concentrate','cod liver oil','algal oil','algae oil',
  'conjugated linoleic acid','clara',
  'calcium','calcium carbonate','calcium citrate','calcium phosphate',
  'magnesium','magnesium citrate','magnesium carbonate','magnesium oxide',
  'iron','ferrous fumarate','ferrous gluconate','iron bisglycinate',
  'zinc','zinc citrate','zinc gluconate','zinc sulfate','zinc bisglycinate',
  'selenium','sodium selenite','selenomethionine','selenium yeast',
  'chromium','chromium picolinate','chromium chloride',
  'copper','copper gluconate','copper sulfate','copper bisglycinate',
  'manganese','manganese gluconate','manganese sulfate',
  'iodine','potassium iodide','potassium iodate','iodized salt',
  'molybdenum','sodium molybdate','ammonium molybdate',
  'potassium','potassium chloride','potassium citrate','potassium sorbate',
  'silicon','silica','silicon dioxide','silicagel','silicium dioxide',
  'chitosan','chitin','glucosamine','glucosamine sulfate','chondroitin',
  'coenzyme q10','coq10','ubiquinol','ubidecarenone',
  'l-carnitine','acetyl-l-carnitine','carnitine','l-carnitin',
  'creatine','creatine monohydrate','creapure',
  'beta-alanine','bcaa','branched chain amino acids','amino acids',
  'tryptophan','5-htp','gaba','gamma-aminobutyric acid',
  'melatonin','dimethylaminoethanol','dmaae','dmaa',
  'taurine','inosine','inositol','tyrosine','n-acetyl tyrosine',
  'alpha lipoic acid','ala','r-lipoic acid','lipoic acid',
  'resveratrol','quercetin','rutin','hesperidin','Diosmin',
  'probiotic','probiotics','lactobacillus','bifidobacterium',
  'prebiotic','prebiotics','galactooligosaccharide','gos','fos',
  'squalene','phytosterol','phytosterol ester','plant sterol','plant stanol',
  'conjugated linoleic acid','CLA',
  'medium chain triglyceride','MCT','MCT oil','triglyceride',
  'oil','fat','fats','oils',
  'hydrogenated','partially hydrogenated','fully hydrogenated',
  'interesterified','fractionated',
  'acid','acids','fatty acid','saturated','unsaturated','polyunsaturated',
  'monounsaturated','trans fat','trans fatty acid',
  'amino acid','essential amino acid','branched chain',
  'enzyme','enzymes','enzyme preparation','transglutaminase',
  'culture','cultures','starter culture','lactic acid culture',
  'probiotic culture','bacterial culture',
  'spice','spices','herb','herbs','herb blend','spice blend',
  'extract','extracts','concentrate','concentrates',
  'powder','powders','dried','dehydrated','freeze-dried',
  'paste','puree','mash','slice','chopped','ground',
  'natural','synthetic','organic','conventional',
  'allspice','bay leaf','bay leaves','cardamom','cardamom pods',
  'celery seed','celery salt','chervil','chili flakes','chili powder',
  'chives','cloves','coriander leaves','corn starch','cracked pepper',
  'cream of tartar','curry powder','dill seed','fennel seed','fenugreek',
  'garam masala','garlic flakes','garlic powder','ginger ground','ginger root',
  'horseradish','juniper','lavender','lemongrass','lovage','mace ground',
  'marjoram','mustard','mustard powder','mustard seed','nutmeg ground',
  'orange peel','oregano','paprika','black pepper','white pepper','peppercorn',
  'poppy seed','rose hip','saffron','sage ground','savory','spearmint',
  'star anise','tarragon','turmeric ground','vanilla bean','vanilla extract',
  'verjuice','worcestershire sauce',
  'acidifier','acidity regulator','acids','acidity regulators',
  'anti-caking agent','anti-foaming agent','antifoaming agent',
  'antioxidant','antioxidants','binding agent','binding agents',
  'bulking agent','carrier','carriers','color retention agent',
  'firming agent','flour bleaching agent','flour treatment agent',
  'foaming agent','gasing agent','glazing agent','humectant',
  'humectants','leavening agent','leavening agents','packaging gas',
  'preservative','preservatives','propellant','raising agent',
  'sequestrant','sequestrants','stabiliser','stabilisers',
  'sweetener','sweeteners','thickeners','whipping agent',
]);

// ── French ingredient names ───────────────────────────────────────────────────
const FRENCH = new Set([
  'sucre','sel','eau','farine','beurre','crème','lait','poudre de lait',
  'fromage','yaourt','oeuf','oeufs','blanc d oeuf','jaune d oeuf',
  'huile','huile d olive','huile de tournesol','huile de colza','huile de coco',
  'huile de palme','huile de sésame','huile de lin','huile de mais',
  'vinaigre','vinaigre de vin','vinaigre de cidre','vinaigre balsamique',
  'levure','levure chimique','poudre à lever','bicarbonate','bicarbonate de soude',
  'chocolat','cacao','beurre de cacao','masse de cacao','poudre de cacao',
  'café','extrait de café','café soluble','thé','extrait de thé',
  'miel','sirop','sirop de glucose','sirop de fructose','sirop d agave',
  'fructose','glucose','dextrose','saccharose','lactose','maltose',
  'amidon','amidon de maïs','amidon de pomme de terre','amidon modifié',
  'farine de blé','farine de seigle','farine de riz','farine de sarrasin',
  'avoine','flocons d avoine','son d avoine','germe de blé','germe d avoine',
  'protéine','protéine de lait','protéine de soja','protéine de pois',
  'protéine de riz','protéine de lin','concentré de protéines de lactosérum',
  'isolat de protéines de soja','isolat de protéines de pois','isolat de protéines',
  'graisse','graisse végétale','graisse animale','graisse de palme',
  'matière grasse','matière grasse végétale','matière grasse laitière',
  'chair','chair de','viande','bœuf','porc','poulet','dinde','agneau',
  'poisson','saumon','thon','cabillaud','morue','sardine','anchois','hareng',
  'crustacés','crevette','crabe','homard','mollusque','moule','huître',
  'légume','légumes','tomate','oignon','ail','poireau','carotte','céleri',
  'poivron','piment','brocoli','chou','chou-fleur','chou de bruxelles',
  'épinard','laitue','concombre','courgette','aubergine','artichaut',
  'fruit','fruits','pomme','poire','banane','raisin','cerise','fraise',
  'framboise','myrtille','cassis','cranberry','pêche','abricot','prune',
  'mangue','papaye','ananas','datte','figue','raisin sec','écorse d orange',
  'noix','amande','noisette','noix de cajou','pistache','noix du brésil',
  'graine','graine de lin','graines de lin','graines de chia','graines de sésame',
  'graine de tournesol','graine de citrouille','graines de hemp','chanvre',
  'arachide','pâte d arachide','beurre d arachide','huile d arachide',
  'soja','graine de soja','protéine de soja','lécithine de soja','huile de soja',
  'tofu','tempeh','miso','sauce de soja','shoyu','tamari',
  'extrait','extrait de','concentré','concentré de','poudre','poudre de',
  'agent','agents','émulsifiant','émulsificateurs','stabilisant','stabilisants',
  'épaississant','épaississants','gélifiant','gélifiants','agent de texture',
  'acidifiant','acidifiants','régulateur d acidité','antioxygène','antioxydants',
  'conservateur','conservateurs','édulcorant','édulcorants','édulcorant de',
  'lécithine','lécithine de tournesol','lécithine de soja','lécithine de colza',
  'arôme','arômes','arôme naturel','arômes naturels','arôme artificiel',
  'colorant','colorants','colorant alimentaire','farbe','lebensmittelfarbstoff',
  'sel nitrité','sel de nitrite','nitrate','nitrate de','nitrite de',
  'phosphate','phosphate de','polyphosphate','diphosphate',
  'citrate','citrate de','ascorbate','ascorbique','tocophérol','tocopherols',
  'carraghénane','carraghénane','gomme','gomme de','gomme arabique','gomme xanthane',
  'guar','farine de guar','tara','tamarindi','tamarin','psyllium','graines de psyllium',
  'cellulose','celluloseg','méthylcellulose','carboxyméthylcellulose','c mc',
  'lécithine','lécithine de tournesol','lécithine de soja','lécithine de colza',
  'protéine de lactosérum','concentré de protéines de lactosérum',
  'lactosérum','poudre de lactosérum','babeurre','poudre de babeurre',
  'crème','crème fraîche','crème aigre','crème sure','smétana',
  'fromage','fromage fondu','fromage rapé','poudre de fromage',
  'malt','extrait de malt','sirop de malt','farine maltée','poudre de malt',
  'fibres','fibres alimentaires','fibres','cellulose','fibres de',
  'pectine','amidon','inuline','oligofructose','fructo-oligosaccharides',
  'culture','cultures','culture lactique','culture starter','ferments lactiques',
  'enzyme','enzymes','enzyme de','transglutaminase','présure',
  'vitamine','vitamines','minéral','minéraux','oligo-élément','oligo-éléments',
  'oméga-3','oméga-6','dha','epa','ala','acide linoléique conjugué','cla',
  'huile de poisson','concentré d huile de poisson','huile de foie de morue',
  'huile d algues','spirulline','chlorelle','wakam','nori','varech','kelp',
  'extrait de romarin','extrait de raisin','extrait de pépin de pamplemousse',
  'coenzyme q10','coenzyme q','ubiquinol','ubidecarénone',
  'l-carnitine','acétyl-l-carnitine','carnitine','créatine','créatine monohydrate',
  'bêta-alanine','acides aminés à chaîne ramifiée','bc aa','tryptophane','5-htp','gaba',
  'mélatonine','inositol','tyrosine','acide alpha-lipoïque','ala',
  'probiotique','probiotiques','prébiotique','prébiotiques','lactobacillus','bifidobacterium',
  'gélatine','gélatine de','collagène','peptides de collagène',
  'graisse','graisses','matières grasses',
]);

// ── E-number whitelist (all EU food additive numbers) ────────────────────────
// Generates all valid E-number ranges per EU food additive regulations.
// Having extra invalid codes in the set is harmless (they won't appear in real data).
function generateENumbers() {
  const s = new Set();
  for (let n = 100; n <= 199; n++) {
    s.add('e' + n);
    s.add('e' + n + 'a');
    s.add('e' + n + 'b');
  }
  for (let n = 200; n <= 299; n++) s.add('e' + n);
  for (let n = 300; n <= 399; n++) s.add('e' + n);
  for (let n = 400; n <= 499; n++) s.add('e' + n);
  for (let n = 500; n <= 599; n++) s.add('e' + n);
  for (let n = 600; n <= 699; n++) s.add('e' + n);
  for (let n = 700; n <= 799; n++) s.add('e' + n);
  for (let n = 800; n <= 899; n++) s.add('e' + n);
  for (let n = 900; n <= 999; n++) s.add('e' + n);
  for (let n = 1100; n <= 1799; n++) s.add('e' + n);
  return s;
}
const E_NUMBERS = generateENumbers();

// ── Combined set ─────────────────────────────────────────────────────────────
export const KNOWN_INGREDIENTS = new Set([
  ...GERMAN,
  ...ENGLISH,
  ...FRENCH,
  ...E_NUMBERS,
]);

// ── Whitelist-check function ────────────────────────────────────────────────────
/**
 * Returns true if the normalized (lowercase, trimmed) ingredient segment
 * is a known/valid food ingredient.
 */
export function isKnownIngredient(normalized) {
  if (!normalized || normalized.length < 2) return false;
  return KNOWN_INGREDIENTS.has(normalized);
}
